# Download and process BAST traffic count data
Source: https://www.bast.de/BASt_2017/DE/Verkehrstechnik/Fachthemen/v2-verkehrszaehlung/zaehl_node.html

In [1]:
import os
import requests

import geopandas as gpd
import numpy as np
import pandas as pd

from zipfile import ZipFile
from bs4 import BeautifulSoup

### Functions for download 
Functions for download and unzip BAST hourly data

In [2]:
#actual downloading -> Author: Johannes Gensheimer
def DownloadURL(url, save_path):
    #function from: https://stackoverflow.com/questions/9419162/download-returned-zip-file-from-url/14260592
    
    chunk_size=128
    r = requests.get(url, stream=True)
    with open(save_path, 'wb') as fd:
        for chunk in r.iter_content(chunk_size=chunk_size):
            fd.write(chunk)

#call download and unzip
def DownloadHourData_BAST(CounterNumber, year, FolderSave):

    BAST_Link = 'https://www.bast.de/videos/' + str(year) + '/zst' + str(CounterNumber) + '.zip'
    FileName = FolderSave + 'zst' + str(CounterNumber) + '_' + str(year) + '.zip'
    #download zip
    DownloadURL(BAST_Link, FileName)
    
    #unzip file if downloading was successfull
    try:
        zf = ZipFile(FileName, 'r')
        zf.extractall(FolderSave)
        zf.close()
        #remove zip file
        os.system('rm ' + FileName)
        return True
    except:
        print('Error while unzipping file: ' + FileName)
        return False

def DownloadRawData_BAST(year, FolderSave, link):
    FileName = FolderSave + 'DZ_' + str(year) + '_Rohdaten.zip'
    #download zip
    DownloadURL(link, FileName)
    
    #unzip file if downloading was successfull
    try:
        zf = ZipFile(FileName, 'r')
        zf.extractall(FolderSave)
        zf.close()
        #remove zip file
        os.system('rm ' + FileName)
        #return True
    except:
        print('Error while unzipping file: ' + FileName)
        return False
    
    #unzip next level of zip files (for each month)
    for month in range(1, 13):
        FileName = FolderSave + 'DZ_' + str(year) + '_' + str(month).zfill(2) + '_Rohdaten.zip'
        try:
            zf = ZipFile(FileName, 'r')
            zf.extractall(FolderSave)
            zf.close()
            #remove zip file
            os.system('rm ' + FileName)
        except:
            print('Error while unzipping file: ' + FileName)
    return True

### Function to process download request 
DZ_Nr_unique: Number of counting stations <br>
years: years that should be downloaded <br>
path: path to temp directory where the downloaded data is temporary stored <br>
keepOrigData: Bool if downloaded raw data should be deleted: True: not deleted, False: deleted <br>

In [3]:
def Process(DZ_Nr_unique, years, path, keepOrigData):

    #sort years array ascending
    years.sort()
    print(years)
    
    #create temporary directory
    if not os.path.exists(path):
        os.system('mkdir ' + path)

    #total number of counting stations that should be processed
    total_count = len(DZ_Nr_unique)

    #some prints
    print('All counter stations: ', DZ_Nr_unique)
    print('In total # = ', total_count)
    count = 1
    
    # empty dataframe for all data
    df_all = pd.DataFrame()
    
    #loop over all counting stations
    for nr in range(0,len(DZ_Nr_unique)):
        
        DZ_Nr = DZ_Nr_unique[nr]
        print('Processing ' , count, ' of ', total_count)
        count = count + 1
        
        #loop over years
        for year in years:
            
            #filename in temp dir
            f = 'zst' + str(DZ_Nr) + '_' + str(year) + '.csv'
            try:
                #download data
                DownloadHourData_BAST(DZ_Nr, year, path) # if download was successfull
                #read data
                df = pd.read_csv(path+f, delimiter=';')
                df_all = pd.concat([df_all, df], axis = 0)
                    
                #remove downloaded file if keepOrigData not True
                if not keepOrigData:
                    os.system('rm ' + path + f)
            except Exception as e:
                print("Could not download data for:"+str(DZ_Nr_unique[nr])+"/"+str(year))

    return df_all

def Process_raw(years, temp_path):
    #Find all links to zip files for the specified years on the BAST website
    BAST_Link = 'https://www.bast.de/DE/Publikationen/Daten/Verkehrstechnik/DZ.html'
    response = requests.get(BAST_Link)
    soup = BeautifulSoup(response.text, 'html.parser')
    links = soup.find_all('a', href=lambda x: x and '.zip' in x and any(str(v) in x for v in years))

    for tag in links:
        link = tag.get('href', None)
        if link is not None:
            matched = [v for v in years if str(v) in link].pop()
            print(matched)
            DownloadRawData_BAST(matched, temp_path, link) # download and unzip raw data for the specified year
            print(link)

In [4]:
def delete_unused_locations(location_list, path):
    locations = ['BY' + str(location) for location in location_list]
    print(locations)
    # print(f"Deleting data of unused locations")
    for folder in os.listdir(path):
        if folder == '.DS_Store': continue
        new_path = os.path.join(path, folder)
        for file in os.listdir(new_path):
            temp_path = os.path.join(new_path, file)
            #print(os.listdir(temp_path))
            print(temp_path)
            print(os.path.isfile(temp_path))
            print("test")
            if os.path.isfile(temp_path) and not (str(file[:6]) in locations):
                print("delete")
                os.system('rm ' + temp_path)

In [5]:
def extract_append_raw_data(df_old, path, newFile='BAST_CountingStations_daily_new.csv'):
     
    for folder in os.listdir(path):
        if folder == '.DS_Store': continue
        print(f"Processing {folder}")
        new_path = os.path.join(path, folder + '/')
        for file in os.listdir(new_path):

            # Handle header rows individually, due to different number of elements
            df_header1 = pd.read_csv(new_path + file, encoding= 'unicode_escape', nrows=1, header=None, sep=r'\s+')
            df_header2 = pd.read_csv(new_path + file, encoding= 'unicode_escape', nrows=1, header=None, sep=r'\s+', skiprows=1)
            df_header3 = pd.read_csv(new_path + file, encoding= 'unicode_escape', nrows=1, header=None, sep=r'\s+', skiprows=2)

            # Copy Dataframe Schema
            df_new = pd.DataFrame().reindex_like(df_old).dropna()
            df_body = pd.read_csv(new_path + file, encoding= 'unicode_escape', skiprows=3, header=None,  sep=r'\s+')   
            
            # Drop faulty line (necessary because of measurements in march for some reason)
            df_body = df_body.drop(df_body[df_body[0].astype(str).str.contains('i', regex=False)].index)

        # Extract data from header
            df_new['Datum'] = df_body[0]
            df_new['Stunde'] = df_body[1].str.split(":").str[0].astype(int)
            df_new['KFZ_R1'] = df_body[2]
            df_new['Wotag'] = pd.to_datetime(df_new['Datum'].astype(str), format='%y%m%d').dt.weekday
            df_new['Wotag'] += 1 # dt.weekday specifies Monday=0 .. Sunday=6

            # Fill NaN's with 0
            df_new = df_new.fillna(0)

            # Extract necessary information
            df_new = df_new.assign(TKNR=df_header1.iloc[0, 0][1:5])
            df_new = df_new.assign(Zst = df_header1.iloc[0, 0][5:9])
            df_new = df_new.assign(Land = df_header1.iloc[0, 1])
            df_new = df_new.assign(Strklas = df_header1.iloc[0, 2])
            df_new = df_new.assign(Strnum = df_header1.iloc[0, 3])
            df_new = df_new.assign(Fahrtzw = 'n')

            # number of lanes in each direction
            lanes_per_direction = [int(df_header2.iloc[0, 0][1:]), int(df_header2.iloc[0, 1])]
            offset_date_time = 2
            offset_kfz_sv = 2 * (lanes_per_direction[0] + lanes_per_direction[1])

            # For some reason 1 station is different than all the other stations..
            if 'BY9223' in file:
                column = 'KFZ_R'

                for direction in range(2): # code only works for 2 directions
                    # KFZ and LKW (SV)
                    count_name = column + str(direction + 1)
                    check_name = 'K_' + column + str(direction + 1)
                    df_temp_count = df_body.iloc[:][offset_date_time + (direction * lanes_per_direction[0])].str.strip().str[:-1].astype(int)
                    df_temp_check = df_body.iloc[:][offset_date_time + (direction * lanes_per_direction[0])].str.strip().str[-1:]
                    for lane in range(1, lanes_per_direction[direction]):
                        df_temp_count += df_body.iloc[:][offset_date_time + (direction * lanes_per_direction[0]) + lane].str.strip().str[:-1].astype(int)

                    df_new[count_name] = df_temp_count
                    df_new[check_name] = df_temp_check
            else: 

                columns_kfz_lkw = ['KFZ_R', 'Lkw_R']
                columns_rest = ['Mot_R', 'Pkw_R', 'Lfw_R', 'PmA_R', 'Bus_R',
                                'LoA_R', 'Lzg_R', 'Sat_R', 'Son_R'] # attention, Lzg = LmA + Sat
                columns_calc = ['PLZ_R', 'Lzg_R'] # Lzg = LmA + Sat, PLZ = Mot + Pkw + Lfw

                for direction in range(2):
                    # KFZ and LKW (SV)
                    for idx, column in enumerate(columns_kfz_lkw):
                        count_name = column + str(direction + 1)
                        check_name = 'K_' + column + str(direction + 1)
                        df_temp_count = df_body.iloc[:][offset_date_time + idx + (direction * 2 * lanes_per_direction[0])].str.strip().str[:-1].astype(int)
                        df_temp_check = df_body.iloc[:][offset_date_time + idx + (direction * 2 * lanes_per_direction[0])].str.strip().str[-1:]
                        for lane in range(1, lanes_per_direction[direction]):
                            df_temp_count += df_body.iloc[:][offset_date_time + idx + (direction * 2 * lanes_per_direction[0]) + (2 * lane)].str.strip().str[:-1].astype(int)

                        df_new[count_name] = df_temp_count
                        df_new[check_name] = df_temp_check
                    # Other classes
                    for idx, column in enumerate(columns_rest):
                        count_name = column + str(direction + 1)
                        check_name = 'K_' + column + str(direction + 1)
                        df_temp_count = df_body.iloc[:][offset_date_time + offset_kfz_sv + idx + (direction * 9 * lanes_per_direction[0])].str.strip().str[:-1].astype(int)
                        df_temp_check = df_body.iloc[:][offset_date_time + offset_kfz_sv + idx + (direction * 9 * lanes_per_direction[0])].str.strip().str[-1:]
                        for lane in range(1, lanes_per_direction[direction]):
                            df_temp_count += df_body.iloc[:][offset_date_time + offset_kfz_sv + idx + (direction * 9 * lanes_per_direction[0]) + (9 * lane)].str.strip().str[:-1].astype(int)
                        df_new[count_name] = df_temp_count
                        df_new[check_name] = df_temp_check

                    # Lzg = LmA + Sat
                    df_new['Lzg_R' + str(direction + 1)] += df_new['Sat_R' + str(direction + 1)]
                    # PLZ = Mot + Pkw + Lfw
                    df_new['PLZ_R' + str(direction + 1)] = df_new['Mot_R' + str(direction + 1)] + df_new['Pkw_R' + str(direction + 1)] + df_new['Lfw_R' + str(direction + 1)]
                    df_new['K_PLZ_R' + str(direction + 1)] = df_new['K_Mot_R' + str(direction + 1)] # Not sure how to handle this  
            df_old = pd.concat([df_old, df_new])
        print(f"Completed {folder}")
    print(f"Writing to file {newFile}")
    df_old.to_csv(newFile)
    return df_old

# Run the functions

In [6]:
bast_locations = gpd.read_file('bast_locations_selected.gpkg')
station_ids = np.array(bast_locations['MST_ID'].unique()) # counting station number

years = np.array([2023]) # years of interst

# download processed datasets from BAST homepage
df_daily = Process(station_ids, years, path='temp/', keepOrigData=False)
df_daily.to_csv('BAST_CountingStations_daily_until2022.csv')

[2023]
All counter stations:  [9140 9141 9772 9773 9082 9003 9083 9115 9066 9063 9242 9064 9217 9006
 9987 9986 9985 9151 9043 9222 9106 9207 9775 9774 9215 9212 9213 9220
 9219 9218 9211 9155 9228 9244 9229 9221 9830 9820 9810 9320 9102 9988]
In total # =  42
Processing  1  of  42
Processing  2  of  42
Processing  3  of  42
Processing  4  of  42
Error while unzipping file: temp/zst9773_2023.zip
Could not download data for:9773/2023
Processing  5  of  42
Processing  6  of  42
Processing  7  of  42
Processing  8  of  42
Error while unzipping file: temp/zst9115_2023.zip
Could not download data for:9115/2023
Processing  9  of  42
Processing  10  of  42
Processing  11  of  42
Processing  12  of  42
Processing  13  of  42
Processing  14  of  42
Processing  15  of  42
Processing  16  of  42
Error while unzipping file: temp/zst9986_2023.zip
Could not download data for:9986/2023
Processing  17  of  42
Error while unzipping file: temp/zst9985_2023.zip
Could not download data for:9985/2023
Processing  18  of  42
Processing  19  of  42
Processing  20  of  42
Processing  21  of  42
Processing  22  of  42
Processing  23  of  42
Processing  24  of  42
Processing  25  of  42
Error while unzipping file: temp/zst9215_2023.zip
Could not download data for:9215/2023
Processing  26  of  42
Error while unzipping file: temp/zst9212_2023.zip
Could not download data for:9212/2023
Processing  27  of  42
Processing  28  of  42
Processing  29  of  42
Processing  30  of  42
Error while unzipping file: temp/zst9218_2023.zip
Could not download data for:9218/2023
Processing  31  of  42
Error while unzipping file: temp/zst9211_2023.zip
Could not download data for:9211/2023
Processing  32  of  42
Processing  33  of  42
Error while unzipping file: temp/zst9228_2023.zip
Could not download data for:9228/2023
Processing  34  of  42
Processing  35  of  42
Processing  36  of  42
Processing  37  of  42
Processing  38  of  42
Processing  39  of  42
Processing  40  of  42
Processing  41  of  42
Error while unzipping file: temp/zst9102_2023.zip
Could not download data for:9102/2023
Processing  42  of  42

In [7]:
# Raw data
print(station_ids)
# create temporary directory to save raw data for the raw data download  
temp_path = 'temp_raw/'
if not os.path.exists(temp_path):
    os.makedirs(temp_path)
# Download raw data from BAST can be performed manually from the follwowing link and unzipped into the temp_raw/ folder
# URL = 'https://www.bast.de/DE/Publikationen/Daten/Verkehrstechnik/DZ.html'
# the downloaded zip file contains zip files for each month
years_raw = [2024] # select the years for which raw data should be downloaded
Process_raw(years_raw, temp_path) # get links for raw data download for the specified years

# Remove stations not in DZ_Nr_arr
delete_unused_locations(station_ids, temp_path)
# extract and append raw data to previous df
extract_append_raw_data(df_daily, temp_path, 'BAST_CountingStations_daily_until2024.csv')

[9140 9141 9772 9773 9082 9003 9083 9115 9066 9063 9242 9064 9217 9006
 9987 9986 9985 9151 9043 9222 9106 9207 9775 9774 9215 9212 9213 9220
 9219 9218 9211 9155 9228 9244 9229 9221 9830 9820 9810 9320 9102 9988]
2024
https://files.bast.de/index.php/s/Dtb5EW44mXzjHnA/download/DZ_2024_Rohdaten.zip
['BY9140', 'BY9141', 'BY9772', 'BY9773', 'BY9082', 'BY9003', 'BY9083', 'BY9115', 'BY9066', 'BY9063', 'BY9242', 'BY9064', 'BY9217', 'BY9006', 'BY9987', 'BY9986', 'BY9985', 'BY9151', 'BY9043', 'BY9222', 'BY9106', 'BY9207', 'BY9775', 'BY9774', 'BY9215', 'BY9212', 'BY9213', 'BY9220', 'BY9219', 'BY9218', 'BY9211', 'BY9155', 'BY9228', 'BY9244', 'BY9229', 'BY9221', 'BY9830', 'BY9820', 'BY9810', 'BY9320', 'BY9102', 'BY9988']
temp_raw/DZ_2024_08_Rohdaten/BY9394.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3455.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6905.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6426.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3361.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5031.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0128.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5175.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1131.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1709.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9593.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HH2234.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4269.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9031.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0324.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9159.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6334.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3341.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4325.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8678.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9104.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6836.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8961.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8623.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6651.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5060.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1747.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1682.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9151.248
True
test
temp_raw/DZ_2024_08_Rohdaten/HE6669.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7141.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9751.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7155.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5255.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6808.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6965.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7419.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6834.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1119.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3427.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9510.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1170.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8091.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6585.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4231.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BE2063.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7435.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4462.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5146.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3805.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9001.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6311.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6853.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5105.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4456.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4157.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3610.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6896.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9063.248
True
test
temp_raw/DZ_2024_08_Rohdaten/RP7838.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6407.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7110.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1109.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9213.248
True
test
temp_raw/DZ_2024_08_Rohdaten/MV1612.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7044.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3893.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9012.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5633.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9589.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0172.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8542.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5126.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6212.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7563.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5153.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6615.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9220.248
True
test
temp_raw/DZ_2024_08_Rohdaten/SH1265.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3677.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5354.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9013.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0134.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0300.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6877.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8801.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8746.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9529.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6833.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9580.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9194.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6923.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7774.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5274.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9352.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4324.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1737.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0103.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6380.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9148.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6393.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3808.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9082.248
True
test
temp_raw/DZ_2024_08_Rohdaten/HE6890.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0153.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1160.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5047.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9232.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9651.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5018.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5230.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6849.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8020.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9183.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3836.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5097.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0154.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7459.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9299.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7909.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6884.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9185.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6866.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3319.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9055.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9572.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8051.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6601.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9193.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9002.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9059.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8013.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9144.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6588.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5342.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3332.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7903.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9274.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5506.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5636.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9303.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8036.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4119.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6400.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0404.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8073.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9754.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1161.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1158.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5311.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8156.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5680.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5650.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3423.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7086.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3475.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9204.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0142.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4461.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3301.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6900.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6954.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9231.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5172.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5171.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9110.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0243.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1702.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3320.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6712.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3902.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0304.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7119.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6886.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3860.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8012.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6405.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3425.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7014.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3470.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5670.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5049.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5122.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9042.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4237.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4349.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3360.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3602.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9283.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3810.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7783.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8453.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5357.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9124.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5168.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9513.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5075.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3821.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5366.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1108.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6851.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1703.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9298.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3849.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6837.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5243.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8001.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3718.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1726.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9195.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0136.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3431.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8016.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9820.248
True
test
temp_raw/DZ_2024_08_Rohdaten/NI3443.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9307.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4118.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0185.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4476.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1744.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9081.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3897.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6516.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5021.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8690.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3411.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6661.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5124.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5082.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8441.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4355.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3416.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3928.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5133.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9991.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3318.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3415.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9289.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7131.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3375.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9016.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6868.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5372.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0194.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9109.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7982.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4361.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6994.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9291.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9960.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5110.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3608.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1707.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3466.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0141.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5208.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1681.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6815.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0246.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9775.248
True
test
temp_raw/DZ_2024_08_Rohdaten/SH1189.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3464.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5325.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5675.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3900.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3350.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7446.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5316.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7201.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4203.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3686.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9534.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6811.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6493.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9526.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0267.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0183.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5238.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3322.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9988.248
True
test
temp_raw/DZ_2024_08_Rohdaten/BY9548.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/ST3898.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9007.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6756.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1164.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9301.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6641.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6835.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3352.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4213.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5163.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6390.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9621.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3434.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5343.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4337.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9135.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8301.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3366.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5380.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5064.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9950.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4102.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7442.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5629.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9254.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9521.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1106.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5158.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5373.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/RP7604.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6790.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6503.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5104.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9262.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5013.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6825.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BW8340.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3380.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/MV1615.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3613.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9165.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SN4162.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6370.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3436.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1192.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6304.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BE2062.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SH1270.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9385.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9966.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/TH4382.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NW5355.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9234.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/SL0279.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/NI3316.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BY9093.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/HE6930.248
True
test
delete
temp_raw/DZ_2024_08_Rohdaten/BB3635.248
True
test
delete

,TKNR,Zst,Land,Strklas,Strnum,Datum,Wotag,Fahrtzw,Stunde,KFZ_R1,...,Bus_R2,K_Bus_R2,LoA_R2,K_LoA_R2,Lzg_R2,K_Lzg_R2,Sat_R2,K_Sat_R2,Son_R2,K_Son_R2
0,7834,9140,9,A,8,230101,7,s,1,88,...,0,a,0,a,0,a,0,a,0,a
1,7834,9140,9,A,8,230101,7,s,2,259,...,0,a,0,a,0,a,0,a,0,a
2,7834,9140,9,A,8,230101,7,s,3,268,...,0,a,0,a,0,a,0,a,0,a
3,7834,9140,9,A,8,230101,7,s,4,160,...,0,a,0,a,0,a,0,a,0,a
4,7834,9140,9,A,8,230101,7,s,5,96,...,0,a,0,a,0,a,0,a,0,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,7935,9083,9,A,8,241231,2,n,20,560,...,0,-,1,-,2,-,1,-,0,-
740,7935,9083,9,A,8,241231,2,n,21,353,...,0,-,0,-,1,-,1,-,0,-
741,7935,9083,9,A,8,241231,2,n,22,288,...,1,-,0,-,1,-,1,-,0,-
742,7935,9083,9,A,8,241231,2,n,23,293,...,1,-,0,-,1,-,1,-,0,-
743,7935,9083,9,A,8,241231,2,n,24,183,...,0,-,1,-,0,-,0,-,0,-

In [8]:
df_test = pd.read_csv('BAST_CountingStations_daily_until2024.csv', index_col=0).sort_values('Datum')
df_test['Datum'].max()

np.int64(241231)

In [9]:
#df_test = pd.read_csv('BAST_CountingStations_daily_until2022.csv', index_col=0)

df_daily.tail()

,TKNR,Zst,Land,Strklas,Strnum,Datum,Wotag,Fahrtzw,Stunde,KFZ_R1,...,Bus_R2,K_Bus_R2,LoA_R2,K_LoA_R2,Lzg_R2,K_Lzg_R2,Sat_R2,K_Sat_R2,Son_R2,K_Son_R2
8755,7734,9988,9,B,471,231231,7,s,20,192,...,0,-,1,-,0,-,0,-,0,-
8756,7734,9988,9,B,471,231231,7,s,21,145,...,0,-,2,-,0,-,0,-,0,-
8757,7734,9988,9,B,471,231231,7,s,22,108,...,0,-,1,-,0,-,0,-,0,-
8758,7734,9988,9,B,471,231231,7,s,23,101,...,1,-,0,-,0,-,0,-,0,-
8759,7734,9988,9,B,471,231231,7,s,24,90,...,0,-,1,-,2,-,2,-,0,-